# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


oneflow-skin    : "jetback" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Jetback Cleaning"
description: >- 
  Professional Jet Washing – Driveways, Patios, Windows & More
title_separator          : "-"
subtitle                 : " " # Displayed in the masthead below the title, use " " for no subtitle
url                      : "https://jetback.co.uk" # the base hostname & protocol for your site
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "perstarke-webdev/oneflow-jekyll-theme" # GitHub username/repo-name
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/logo.png" # Site logo displayed in the masthead
show-popup               : false # set to false if you don't need / want to show a cookie-banner / cdn-usage popup.
                                # Edit the popup itself in the respective /includes file
masthead_title           : " "  # Overrides the website title displayed in the masthead, use " " for no title
sticky-masthead          : true # if true, masthead/navigation bar will stay visible when the user scrolls down.
                                # if false, it will move out of sight when scrolling.
masthead-opacity         : 0.85 # set to any value between 0 and 1.
                                # 0.8-0.9 is a good recommended starting point. Only relevant if masthead is sticky.
background-image         : # '/assets/images/header.webp' # Remove / out-comment, if you don't want a background image
background-image-mobile  : # '/assets/images/header.webp' # If you want a different (e.g upright) background image for mobile
background-image-overlay : rgba(255, 255, 255, 0.5) # Set overlay for the background image



# Site Footer.
footer:
  links:
    - label: "Email"
      icon: "fa fa-envelope"
      url: "mailto:info@jetback.co.uk"

    - label: "Phone"
      icon: "fa fa-phone"
      url: "tel:07465 653849"

    # - label: "Facebook"
    #   icon: "fab fa-facebook"
    #   url: "https://facebook.com/jetbackcleaning"  # create/replace with your actual page

    # - label: "Instagram"
    #   icon: "fab fa-instagram"
    #   url: "https://instagram.com/jetbackcleaning"  # optional but great for before/after pics

    # - label: "Google Reviews"
    #   icon: "fa fa-star"
    #   url: "https://g.co/kgs/b1cTZ72"  # replace with your Google Business profile

  copyright: "JetBack. All rights reserved."





# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style



# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache



# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

